### ISSUE TITLE
Release apk

### ISSUE THREAD

**Issue by ahmed-tasaly** [fathonyfath/quran-lite-android#2]
Can you create a new release apk?

**Comment by fathonyfath** [comment]
Sure, let me try on weekend and update the release page.

**Comment by fathonyfath** [comment]
Hey, new apk can be found on this release: https://github.com/fathonyfath/quran-lite-android/releases/tag/v1.3.0

The size is increased significantly because I added some new functionality and new app icons compared to the last release. 

Thank you for your interest!
