### ISSUE TITLE
Request Release Candidate

### ISSUE THREAD

**Issue by ogigpermana** [fathonyfath/quran-lite-android#3]
mas bagi source code versi rc 1.3 nya kalo boleh mau nyoba...

**Comment by fathonyfath** [comment]
Bisa pakai commit 31b4326ecbe98f747965ac6bfd775a8ce763a756 ya

**Comment by fathonyfath** [comment]
Tag-nya sudah ku update dengan apa yang kugunakan untuk bikin rilis 1.3.0.

Thanks!
